### ISSUE TITLE
Texturing Issues 

### ISSUE THREAD

**Issue by Megistus** [Nuchaz/BiblioCraft#225]
I use Glimmar's Steampunk, and have been working on Mod Support for your Mod for that texture pack and have run into some graphical nuisances. For example, the default wool textures are made to look like metal plates, but, when applied to your chairs, only two edges of the texture are displayed, making the chair look, well, odd. The same is also found with the various wood textures which cause the textures used to make certain items, again, look odd. And again, found with the forestry support, as textures that support Glimmar's style, do not work very well with shelves, chairs, clocks, etc.

I am not sure what would be easier on you ... I would certain prefer having a full texture sheet for all the items in your pack. However, what may be the easiest solution - at least in my mind - is that you give the option for alternate textures to be applied to the items. Thus, for example, I could create a plain oak wood pattern that would replace the default one out of the texture pack that you are drawing from thus eliminating the texturing issues.

Finally, the texture for the crafting table in Glimmar's is animated, on your crafting table, it won't render, only leaving it white. 

I hope that made some kind of sense, and I have added some screen shots to help illustrate my issues.

Thanks for you excellent mod!

![2015-01-06_08 02 45](https://cloud.githubusercontent.com/assets/6314023/5629639/577d3ffe-957b-11e4-9ae5-b1f57b3ac505.jpg)

![2015-01-06_08 03 00](https://cloud.githubusercontent.com/assets/6314023/5629641/5790353c-957b-11e4-83f1-d82ad0cd64ba.jpg)

![2015-01-06_08 03 07](https://cloud.githubusercontent.com/assets/6314023/5629640/578f4ec4-957b-11e4-8c6c-9dd84b9ca1d4.jpg)

**Comment by Nuchaz** [comment]
Ok, so I think you do have a couple options on some things. Most of the blocks, excluding newer ones such as the workbench, seat, and clocks, do also support full texture sheets. You have to enable them in the config however. The different shelves all have versions with the texture sheets. So that might help with some things.

There is another option which I think may work. All the .obj models used, which is 95% of all BiblioCraft models, also use the resource pack system. I am pretty sure you can put models in your resource pack and replace the ones I have. So what that means for you in your situation is if you wanted to you could load up the .obj models in a modeling program (such as Blender, 3dsmax, maya, modo, etc.) and change the UV mapping to suit your textures. When I originally UV mapped these models, I only mapped them to fit vanilla textures and just hoped for the best on anything else. But this would give you 100% control on how the texture is applied to the model. I haven't tested the obj models in resource packs personally, so I don't know 100%, but I have reason to believe it should work just fine.

On the animated texture, that kind of has me stumped as to why that didn't show. I don't know of anything I could do to fix it either. I apply the textures in the TileEntitySpecialRenderer with the bindTexture method, which is, as far as I know, the only way to apply textures in a TESR. Maybe there is some general issue with TESR's and animated texture. That one might require more research to figure out.

**Comment by Megistus** [comment]
Okay ... I have poked around with the OBJ files and coming up short. I have not slung code in quite a number of years and working with 3d files just is outside of what I have time for right now. But ... as far as I can tell, the code that supports what texture gets applied to the OBJ file is somewhere in your source code, not the OBJ file itself. And, from what my aged knowledge of programing is, I am going to make the following assumptions. When Minecraft calls and renders the object, say a shelf, the code tells it to use the OBJ file and then to apply a texture over it separately as you use the same OBJ file for all the different woods, just applying the different textures as required all from within the Class file. 

So, where I am hitting difficulty is that I am not so worried about 'how' the texture file is being applied, but, 'what' texture file is getting applied, and that particular pointer is located in the class file. 

Is there any possibility that you could config the texture pointers in your class files to point at the default textures, but, allow for editing so as to point at different textures? Set up somehow similarly to the CTM format found with MCPatcher?

This seems to be the most expedient solution as rendering an individual texture map for each object is something that you are not interested in doing, as it is more expedient to use existing textures. 

...

Then, of course, it may become a moot point anyway as it looks as if the JSON format will have the texture locations formatted within the scripting of the 3d model anyway ... and it may just be best to wait until you convert your models to that format - as I recall reading earlier.

Thoughts?

**Comment by Nuchaz** [comment]
Yeah, you are correct, it is in my code that specifies exactly what texture is applied. Editing the UV map of the model only changes how the textures are applied to the model. Definitely understandable if you don't have the time to get into that, it can be a pretty deep subject. I honestly don't know my way around blender so I can't be of any help on that, I just know that blender is a powerful package thats free. I used my student copy of 3dsmax for most of the BiblioCraft models and I've recently made the move to Modo Indie which I'm liking more than anything I've tried. 

Anyway, It would take quite a bit of rework to be able to expose the strings that point to the textures for the different blacks because they all point to the same texture currently. I'm not familiar with the CTM format found in MCPatcher, but it would be possible to expose that stuff to a config file or something, it just would be more work than I think is worth it when its all got to change to something else anyway because of Minecraft 1.8.

If I find out there are limitations in Minecraft 1.8 I can't get around, I may come back and do another bigger 1.7.10 update and if that is the case maybe I'll see about exposing those texture variables.

The json models could be the ticket, but they seem to have some serious limitations right now. I am still trying to figure out how I can make my current models work in the format. I might have to write some sort of obj to json converter myself to do the business. I'm sure I'll get something figured out though, its just not as simple as I had originally hoped.
