### ISSUE TITLE
Nitor (Thaumcraft) crash

### ISSUE THREAD

**Issue by WolfAmaril** [Nuchaz/BiblioCraft#234]
Every time I try to open an SSP world/Start a new SSP world, I get this

http://pastebin.com/N4Pc7MdJ

Will be posting to thaumcraft issue tracker as well.

**Comment by Nuchaz** [comment]
This is an issue with forge that sometimes causes the black id maps on worlds to get messed up. It sometimes seems to happen when blocks are removed or too many are added at one time when changing / adding / updating / removing mods. There really isn't anything I can do about it that I know of since that is all stuff that happens in vanilla minecraft and forge. All I can really do is suggest trying to load a backed up copy of the world before the problem started. I'm going to close this issue since I can't really do anything about it.

**Comment by WolfAmaril** [comment]
I would like to add that this issue only occurs when moving from a server world to a single player world without restarting your client.
I say this not expecting you to be able to fix it, but because I have no idea who I'd send this information to, and was hoping you'd know, as it seems like something the devs of forge and minecraft would want to be aware of.

**Comment by Nuchaz** [comment]
Ah ok, I think I remember someone else mentioning that same issue awhile back, where they would get that crash from moving from a SMP world to SSP world. I think the best place to report something like that would likely be https://github.com/MinecraftForge/MinecraftForge/issues
