### ISSUE TITLE
[Suggestion] Bibliowoods for Thaumcraft/Witchery/TwilightForrest?

### ISSUE THREAD

**Issue by JAWSAWN** [Nuchaz/BiblioCraft#236]
Will we ever getting those woods from magical mods as addons? That shouldn't be such a big deal since there's not much woods variants on them. Bibliocraft and those mods been here since a long time. Am I the first one to suggest that or don't you like to support those mods?

Keep the good work!

**Comment by Nuchaz** [comment]
I am considering a thaumcraft addons and possibly a witchery though sometime in the nearish future. One important thing is I need slabs to make recipes, so if a wood has no slabs, I can't really setup a BiblioWoods. Thaumcraft actually only just got slabs a couple weeks ago, so prior to that, BiblioWoods wasn't an option. Twilight Forest just converts to vanilla words, there isn't no planks / slabs.

The main reason I haven't came out with many more BiblioWoods addons is because there is a fair amount of work involved in getting all that setup and running. I haven't figured out an easier way that works with how I am doing it yet. 

Closing this issue since we have another with the same stuff mentioned.
