### ISSUE TITLE
[SG] Combine all different material block together

### ISSUE THREAD

**Issue by anion155** [Nuchaz/BiblioCraft#237]
You can place in your TE classes Block indicated material and texture from witch every BiblioCraft block made.
This will allow you to generate all blocks with different material, for example, from config file. So you do not need to use different mod to add more blocks from wood, or the player himself can add such blocks.
For crafting you can NBT tags to ItemStacks before use them in GameRegistry.

**Comment by Nuchaz** [comment]
That is a pretty good idea, but not something I can do for 1.7.10. It would break everyones worlds. in 1.8, everything is changing anyway, so that is an opportunity to do things a little better. 
There is still the issue of recipes, which I could possibly delegate a way to add a line to config file for that too. I think recipes would be the toughest part really. But yeah, I'll definitely be making some changes in 1.8, but for now, this isn't a change I can make unless I want to make lots of people mad at me for breaking their worlds, heh.

**Comment by anion155** [comment]
I don't really know about 1.8 changes in CraftingManger, but here is explained how you can use NBT data(or damage) in crafting http://www.minecraftforge.net/forum/index.php?topic=20157.0
