### ISSUE TITLE
Tape Measure posts stay forever

### ISSUE THREAD

**Issue by Numba90** [Nuchaz/BiblioCraft#238]
I decided to build my spawn at 0,0 but when I went to measure some stuff the posts created by the tape measure stayed there forever. I can't get rid of them either, I can only build around them. [screenshot](http://i.imgur.com/eNOuiyN.png). Rebooting my server didn't help either.
Version: 1.9.2
I'm playing the FTB infinity pack, so it's hard to tell what forge version is being used, I assume it's close to the latest

The tape measure works just fine as long as it isn't being used on x or z of 0

**Comment by Nuchaz** [comment]
interesting. it seems because it seems like there is technically a +0 and a -0 something strange is happening. There is a small place right in the middle of the post that you can hit with your pickaxe and break the poles. I'll have to investigate to see what I can do about it not breaking blocks there, but for now you should be able to manually break the posts, you just have to aim right in the center of the striped post.

**Comment by Nuchaz** [comment]
I found the root of the problem in my code and fixed it, so the next release will properly remove posts.
