### ISSUE TITLE
cannot be cast to jds.bibliocraft 

### ISSUE THREAD

**Issue by Yselith** [Nuchaz/BiblioCraft#241]
Hello,

I got a crash with this logs:

http://pastebin.com/FEcWDssA

**Comment by Nuchaz** [comment]
This is an issue with forge that sometimes causes the black id maps on worlds to get messed up. It sometimes seems to happen when blocks are removed or too many are added at one time when changing / adding / updating / removing mods. There really isn't anything I can do about it that I know of since that is all stuff that happens in vanilla minecraft and forge. All I can really do is suggest trying to load a backed up copy of the world before the problem started. I'm going to close this issue since I can't really do anything about it.
