### ISSUE TITLE
Eternal Compass disapearing when optifine are installed

### ISSUE THREAD

**Issue by renard162** [Nuchaz/BiblioCraft#251]
I'm making a personal modpack and when I using optifine and die (with proper enchanted atlas) the Ethernal Compass rapidly desapear from my inventory/hotbar on respawning.

This problem occur many times but not every time and only when optifine are installed (even with default config).

Mod versions:
Forge: 10.13.2.1291
Bibliocraft: 1.9.2
Optifine: 1.7.10 HD U B5 or 1.7.10 HD B5 (I tested both)

**Comment by Nuchaz** [comment]
Hmmm, this is an odd bug. It almost sounds like the server/client are out of sync (can happen in SSP as well as SMP) so only the client maybe is getting the compass but the server doesn't so the server updates the client which makes it disappear. That is the most logical explanation I can think of for it rapidly disappearing. So that kind of tells us maybe optifine is doing something that messes with forges death / spawn events. If that is really the case, then it would be out of my hands.

If there are any other mods that add items to the player inventory on spawn, that might be a way to kind of test to see if the same thing happens there. I can't think of any mods off the top of my head that do though. Hmmm.

This really is an odd bug. I'll try to investigate a bit sometime. Let me know if you figure out anything else about it.

**Comment by renard162** [comment]
Ok, sorry for late. I take some time testing many things including:

With only Bibliocraft and Optifine changing some java arguments;
On this tests nothing change.

Seraching mods that change player items on death and I found:
-EnderIO have a enchantment (soulbound) that restore enchanted items on death;
-Extra utilities have golden bag of holding that return bag to player on death.

When I'm testing on my modpack I enchanted many items with soulbound (armors, swords, TE bag, jetpack, portable teleporter, TE capacitor and Tinkers' glove), get a golden bag of holding and a eternal compass atlas. ( http://imgur.com/wa8Jk8b )

When I die Eternal compass fast blink in my hotbar then disapear and few moments later (lass than half second) enchanted items appear on my inventory (sorry, I can't take a screenshot at this time, everything occur too fast) ( http://imgur.com/3k42NFc )

P.S. Sorry for my bad English, that's not my native language.

**Comment by Nuchaz** [comment]
Hmmm, interesting. I am thinking maybe the golden bag of holding, or maybe even the EnderIO enchantment, when it updates your inventory with the items you lost, is overwriting the eternal compass. I'll investigate this a bit more, I think I have a better idea now what might be happening.

**Comment by Fabboz** [comment]
Hello,
I have found these settings in the graveston mod config file:

# Configuration file

compatibility {
    B:EnableArsMagicaSoulbound=true
    B:EnableEnderIOSoulbound=true    <<---whatch this
    B:EnableForestryBackpacks=true
    B:EnableTwilightForestCharmsOfKeeping=true
    B:SpawnMoCreaturesMobs=true
    B:StoreBackpacksItems=true
    B:StoreBattlegearItems=true
    B:StoreBaublesItems=true
    B:StoreGalacticraftItems=true
    B:StoreMaricultureItems=true
    B:StoreRpgInventoryItems=true
    B:StoreTheCampingModItems=true
    B:StoreTinkerConstructItems=true
}


is possible that the compass remain on the grave using this mod??

**Comment by Nuchaz** [comment]
With the gravestone mod it should still spawn a compass in your inventory when you die that leads to to your gravestone. That is, if something else isn't messing it up. I'm still not sure why it doesn't work with certain mods. That is something I still haven't been able to figure out.
