### ISSUE TITLE
Can't disconnect tables with screwdriver

### ISSUE THREAD

**Issue by MalkContent** [Nuchaz/BiblioCraft#256]
All tables autoconnect to another and I can't force separate tables with the screwdriver. I vaguely remember that being possible at some point before, but maybe my memory is shoddy.  
In any case, the ability to create separate tables next to each other would be nice :)

**Comment by Nuchaz** [comment]
Yeah, that is intended. Tables have always been like that. I can consider changing their behavior maybe after the 1.8 update. Otherwise I would have to make a change to all the bibliowoods and would have to rewrite most of the table behavior. 

So yeah, quite difficult to change right now, but I'll consider the change when I'm making a game breaking update anyway (like minecraft 1.8). ;)
