### ISSUE TITLE
Request: Bibliowoods Thaumcraft edition

### ISSUE THREAD

**Issue by MalkContent** [Nuchaz/BiblioCraft#266]
As title. TC woods have slabs now and should work with the recipes

**Comment by Nuchaz** [comment]
No need for it now, the newest Bibliocraft has framed blocks that support thaumcraft woods among most other blocks. ;)

**Comment by MalkContent** [comment]
Right :) would it be possible to just generically add recipes for any and all mod wooden planks and make the resulting blocks look like they would look as if they were a framed block with the kind of plank inserted?

**Comment by Nuchaz** [comment]
Unforchantly, no. The recipes were the main reason I had to make the BiblioWoods addons. There are a couple of ways to generally get access to the blocks and slabs of other blocks, but I have to know the specific mod and the specific name of the wood planks to get them. Then there is no good way to align the same types of slabs and planks.  There is just a lot of hands on that is required to get all that working which is another of the reasons I switched to the framed blocks.

**Comment by MalkContent** [comment]
hrm. crappy pseudocode ahead.
[code]woodPlanks = oreDict.getAll("plankWood")
woodSlabs = oreDict.getAll("slabWood")
foreach(woodplank plank : woodPlanks) {
   foreach(woodslab slab : woodSlabs) {
      if(slab.hasRecipeMadeFrom(plank) && (slab.isNotOakSlab XOR plank.isOakPlank) {
         makeRecipeForPlankType(plank, slab);
   }
}[/code]
the resulting item would just be a framed block that is locked as the wood type with a boolean value

**Comment by Nuchaz** [comment]
Hmm, interesting. I wasn't aware I could get arrays of stuff back from the ore dictionary. That could come in handy. 

I still don't really even want to add more recipes. I don't really see a good reason to add more recipes. You can still get the same exact block with the framed blocks. It is just more stuff that clutters up NEI and more recipes that could potentially overlap with other mods. Moving the to framed blocks actually makes designing recipes potentially much easier and safer in the future because I won't have to even consider overlap with any recipes other than my own. Which is one reason why I am considering moving to only framed blocks in Minecraft 1.8.x. (I'm still waiting for .obj model support and some sort of dynamic item rendering support like I have in 1.7.10 with IItemRenderer)

**Comment by MalkContent** [comment]
Agreed on the framed blocks being the only necessary thing. i just thought purely wooden stuff deserved it's own recipe for cheapness and early gameness and stuff. I would make the recipe output the same block as the framed block recipe, just with nbt already containing the wooden block and with no ability to return it to an empty framed block status. Then make a creative tab entry for the oak versions only. Pretty sure you can hide all the different wood versions of framed blocks from NEI, too, if it even shows up in the first place, being the same item just with different nbt.
In my head it's just a gameplay thing that makes the stuff more accessible in the beginning without having to go through the extra steps and setup that making framed blocks requires.

**Comment by Nuchaz** [comment]
Fair point. Might be a good enough reason to keep around recipes for vanilla wood stuff at least going forward. 
Good point about the stuff probably wouldn't show up in NEI either. The atlas / eternal compass enchantment is a crafting recipe that only changes nbt and that doesn't show up in NEI.
