### ISSUE TITLE
You can spawn any item you want

### ISSUE THREAD

**Issue by Shevchik** [Nuchaz/BiblioCraft#294]
The is no filtering in Bibliocraft CustomPayload BiblioClipboard packet, so you can basicly spawn any item you want.

**Comment by Nuchaz** [comment]
Interesting. this definitely sounds like something that needs to be resolved. I'm not exactly clear on how to reproduce this or exactly what needs to be fixed. Maybe you could explain the steps to reproduce this. If you would like, you can use the minecraft forum PM system so to keep the steps on how to do this out of the public. Otherwise I will just edit your message and remove the steps after I read them.

**Comment by oleg599** [comment]
Hack mod: https://mega.co.nz/#!HZ0hjDzR!18CH7BrFes8g7rX0RlisVYlK9F_zR2wWtDQJY0Q1CgI

Drop it to mods folder and press H for open GUI

**Comment by Nuchaz** [comment]
ok, I see, thanks. I'll look into doing something about this when I get some time.

**Comment by AussieWarGod** [comment]
3rd party fix for the issue (I KNOW biblio is closed source, i didn't write it pls don't hate me) 

http://pastebin.com/3yS04sQ2

Figured it would make fixing it easier for you. Happy coding.

**Comment by Nuchaz** [comment]
Thanks, though it looks like they just commented out everything that could possibly be exploited basically breaking bibliocraft to fix the game. But yeah, now that the website is up, this is my next priority and I think I have some ideas on how to fix this so it can't be exploited.

**Comment by kirr9999** [comment]
It is a very good that you are making minecraft mods instead of treating people or construction of skyscrapers.

**Comment by makkarpov** [comment]
Can you remove label "bug" and attach label "backdoor" to this ticket?

**Comment by Nuchaz** [comment]
I have a fix for this will be in the upcoming release, v1.10.5. I am planning to release this weekend after I finish sorting a couple other bugs.
