### ISSUE TITLE
BoP Bibliowoods somehow causes BoP Paralysis Potion to be overwritten by IC2

### ISSUE THREAD

**Issue by KageDragon** [Nuchaz/BiblioCraft#302]
It's really weird...

With just BoP and IC2, they add 3 potions

24: ic2.potion.radiation (ic2.core.IC2Potion)
25: potion.paralysis (biomesoplenty.common.potions.PotionParalysis)
26: potion.possession (biomesoplenty.common.potions.PotionPossession)

but if BoP Bibliowoods is enabled, it changes to this:

24: ic2.potion.radiation,ic2.core.IC2Potion
25: potion.possession,biomesoplenty.common.potions.PotionPossession

using 
IC2 2.2.751
BoP 2.1.0.1364
Bibliocraft 1.10.4
BoP Bibliowoods 1.9
Forge 10.13.4.1472

**Comment by Nuchaz** [comment]
That is really odd, I have no clue why that could even happen. The BoP BiblioWoods doesn't even add any items and shouldn't touch anything with any other mods other than just using some BoP blocks for recipes. 

You might want to consider just dropping BiblioWoods BoP and using the BiblioCraft Furniture Paneler. You can basically achieve the same result with the paneler. I don't plan to update the BiblioWoods addons any more (other than maybe the TFC addon) since the paneler can do the same thing, but should automatically work with all mods and even non-wooden blocks.

**Comment by KageDragon** [comment]
Fair enough...
