### ISSUE TITLE
Dupe using bibliocraft's code

### ISSUE THREAD

**Issue by OxyMethylene** [Nuchaz/BiblioCraft#304]
I believe there was already a ticket about this... but can't find it in the open tickets, neither in the closed tickets.

I run my own server (FTB Infinity) and had some problems with people abusing this bug. They were mainly russians and were able to spawn any block in. We did some research and managed to find the mod they use.
A few weeks later we managed to find the updated version for the mod, so it was compatible with FTb Infinity 1.8.2 but also the fix for servers.

The way the mod works is, you put an extra mod in your mods folder. Ingame you can set a hotkey which will open a GUI. In the gui you get 4 textboxes. One for the itemid, one for metadata, one for the amount and one to set the name to whatever you like. You simply hit enter and the items spawn in the slot you currently have selected.

Since I don't want to give out the hack here... and the fix isn't really 'official' or anything... Is there a way to mail or message you the links somewhere?
I got the 2 versions of the mod and the fix which works on FTBInfinity 1.8.2 (Havnt tested on other versions)

Greetings Oxy

**Comment by OxyMethylene** [comment]
This can be removed... Saw it was already closed on another ticket

Sorry

**Comment by Nuchaz** [comment]
I actually just closed the issue yesterday because I have it fixed in my local codebase and I plan to release later on today. I am into the testing stages right now and want to test a few things. That hack will be impossible after the update, as well as a couple of other dupe bugs. So keep an eye on bibliocraftmod.com later today for an update. :)
