### ISSUE TITLE
Changing ID from the big book

### ISSUE THREAD

**Issue by Arytas** [Nuchaz/BiblioCraft#331]
Hey there

i have a little problem with the Big Writing Book
i created two, with a lot of stuff inside, like short explanaitions to the mods

in addition i use the signshop plugin and want sell the big books
but the problem is, that signshop is using the ids to sell/buy etc. the items
but the id of the big books (sign or not) are always the same.
is there a way to change the ids of the sign books or something like that?

**Comment by Nuchaz** [comment]
I'm afraid there isn't really any easy way to do that. It should technically be possible to put the signed books on another id but I would have to wait till the 1.8.x or whatever version update to do that since it would risk breaking current books. I'll consider doing that in the future though since you highlighted a valid reason to have the signed book on a separate ID.

**Comment by Arytas** [comment]
ok i will waiting for it :)
