### ISSUE TITLE
recipe bork

### ISSUE THREAD

**Issue by AeroyrHwrdd** [Nuchaz/BiblioCraft#350]
Fire is in place of where the slabs should be in recipes for Forestry Bibliowoods. It is confusing. This is not the same for the other Bibliowoods editions, they are fine. Is it doing this because of Forestry 4?

**Comment by 2ndkirbyever** [comment]
I am having this same issue. I wanted to make a Maple shelf, but found I couldn't because the recipe uses fire and not the wood slabs that it is supposed to be using.
![2016-07-17_21 00 04](https://cloud.githubusercontent.com/assets/16438720/16904777/847e4cca-4c61-11e6-918a-1857ea7d8a3b.png)
I don't want to have to use MineTweaker and change every Bibliowoods Forestry recipe so that it matches what it's supposed to be

**Comment by Nuchaz** [comment]
This issue was caused when Forestry updated to version 4, but I quit updating the BIblioWoods because the Furniture Paneler block in BIblioCraft can accomplish the same goal, plus a whole lot more.

**Comment by AeroyrHwrdd** [comment]
I think the only issue I find with the paneller is Soartex texture is a tiny bit strange on the potion shelves, apart from that, the paneller is pretty rad, thank you.
