### ISSUE TITLE
Plumb line shows wrong y-coord

### ISSUE THREAD

**Issue by EzerArch** [Nuchaz/BiblioCraft#367]
As you can see here I'm standing on a surface which its y-coord is 69, but the plumb line says it is 68.
![2016-07-09_18 07 52](https://cloud.githubusercontent.com/assets/6743303/16710301/0f90380e-4600-11e6-8c79-b09964438b8c.png)

If I go onto a 5-block higher surface, the plumb line tells me the correct depth (5 m):
![2016-07-09_18 23 17](https://cloud.githubusercontent.com/assets/6743303/16710385/705e437c-4602-11e6-9c1f-6a767f793097.png)

But still the bottom block's y-coord is wrong:
![2016-07-09_18 26 13](https://cloud.githubusercontent.com/assets/6743303/16710393/a75b8c18-4602-11e6-8328-bddff8c5652c.png)

I opened a 3-block deep hole, the depth shown by plumb line is correct:
![2016-07-09_18 24 00](https://cloud.githubusercontent.com/assets/6743303/16710399/e43d7394-4602-11e6-85f8-f44c62049fa9.png)

But the bottom y-coord is wrong:
![2016-07-09_18 27 07](https://cloud.githubusercontent.com/assets/6743303/16710402/04697a46-4603-11e6-86aa-7a3016120e5d.png)

I don't know if I'm getting thing wrong, I think the intuitive way is to get the y-coord of the top/visible face of the block I'm aiming at in front of me, not the y-coord of the bottom/opposite face.

**Comment by Nuchaz** [comment]
thanks for the detailed report. I'll have a look at this. I thought something seemed off when I was testing the plumb line in my 1.8.9 port I am working on.

**Comment by EzerArch** [comment]
Out of curiosity: is the fix available only in 1.8-1.11?

**Comment by Nuchaz** [comment]
oh yeah, I guess I forgot to check 1.7.10 on this issue before I did those last updates.

**Comment by Nuchaz** [comment]
I just had another look at this and apparently I forgot to roll a fix in any version. I just updated my code in versions for 1.7.10, 1.9.4, 1.10.2, and 1.11.2.  I have plans to release an update for 1.11.2, 1.10.2 and 1.9.4 (1.9.4 is basically effortless, so why not, just a recompile of 1.10.2 version) within the next 24 hours or so. I don't have immediate plans to release a 1.7.10 update, but if and when I do, the fix for this will be rolled into it.
