### ISSUE TITLE
Framed bookcase: side of backside wood pannel missing

### ISSUE THREAD

**Issue by Crazy-KSK** [Nuchaz/BiblioCraft#376]
- Minecraft 1.8.9
- Forge 11.15.1.1902
- BiblioCraft 2.0.0

http://i.imgur.com/C6aRiEN.jpg
only the framed one without a material applied has this issue
after some more investigation I found that most if not all framed blocks without materials applied to them have one or more sides missing like this 
http://i.imgur.com/yFAfcqx.jpg

**Comment by Nuchaz** [comment]
I think this just might be a consequence of how I drew up the frame texture. Since the way these blocks are textured I tried to make it so it supports as many types of textures as possible, it is difficult to get every block to look great with every texture. The framed block texture is more intended as a placeholder texture until you re-texture the block on the furniture paneler. Of course, there is nothing at all wrong with just using the framed blocks as they come, but you might have to live with the texture imperfections.
