### ISSUE TITLE
Framed Chest texture bug when facing north or south

### ISSUE THREAD

**Issue by Crazy-KSK** [Nuchaz/BiblioCraft#378]
- Minecraft 1.8.9
- Forge 11.15.1.1902
- BiblioCraft 2.0.0

http://i.imgur.com/lW5QBd5.jpg
as you can see the north and south facing ones have their top and their bottom differently shaded 
this happens irregardless of materials used

**Comment by Nuchaz** [comment]
This is a known issue that I couldn't work out, but I figured it was minor enough I would let it go.
The problem comes from the fact that the base of the chest and the lid are rendered in 2 different ways. The base uses the new model system with states and all while the lid uses the TESR method that runs every tick. This is so I can animate the lid. If I figure out a way to fix, I will, but no promises on this one.
