### ISSUE TITLE
[1.7.10][Dupe bug]Add some server side checks for the book to prevent client side hacks, 

### ISSUE THREAD

**Issue by wormzjl** [Nuchaz/BiblioCraft#389]
Generally you can use the mod called all-u-want inventory editor to edit the book on the client, creating some weird items and also capable of duping items.

Here is an good example
http://imgur.com/a/cuX4V

This only works with bibliocraft book so far, I think you probably need to check on the server side about what the client sent you.

**Comment by Nuchaz** [comment]
Ok, this will be fixed in the next update. I will roll this fix into the 1.7.10 version, the 1.10.2 version and the upcoming 1.11.2 version. I realized I don't even need to be sending ItemStacks in that packet, that's handled by the container already, so, no more ItemStacks through these packets anymore, that should stop that exploit.
