### ISSUE TITLE
Map pointer when created with Atlas

### ISSUE THREAD

**Issue by Amzeroth** [Nuchaz/BiblioCraft#406]
Hi, i love this mod. But i have just a little issue and i don't know if i overlooked something or what happened. The thing is, when i use the Atlas and set it to auto create a map, the new maps created by the Atlas don't have the little pointer that follows you when you create a map by yourself. This has made that navegating with such maps becomes a little to confusing. Is this an issue? And if so, is there any way to solve it? 

Thanks.

**Comment by Nuchaz** [comment]
This is an issue that has come up in the latest update. I'll try to get this solved soon if I can. I agree it makes the maps more difficult to use.

**Comment by Amzeroth** [comment]
Ah, it's fine. Thanks for the quick reply. And ypu are doing a great job.

**Comment by CovertJaguar** [comment]
I've seen it happen sometimes even with vanilla maps without the mod installed. Restarting usually fixes it there. But I've also seen it with the Atlas, and restarting doesn't fix it.

**Comment by Nuchaz** [comment]
This will be fixed in the next release. Turns out all I had to do was set trackingPosition to true in the MapData to enable player position. I don't think that was a thing prior to MC 1.8.9. So next release coming for MC 1.10.2 and the 1.11.2 version I am working on will have this fixed. New release coming soon.
