### ISSUE TITLE
Clock Timing 1.10.2

### ISSUE THREAD

**Issue by Rahmiel** [Nuchaz/BiblioCraft#414]
This may seem like a completely pointless bug report, but I consider this important on an immersion level. The clock in the current 1.10.2 version has a slight animation problem. The second hand is moving faster than the pendulum is swinging. Now, if you know anything about clocks that use pendulums, the pendulum swinging is what creates the mechanics for the second hand to move. If they are out of sync than that means the second hand is moving of its own free will. I imagine this would be an easy fix.

**Comment by Nuchaz** [comment]
I'll look into this. Something might have gotten messed up in transition from version. Everything has been rewritten since 1.7.10 so I am still getting caught back up to where I was at that time.

**Comment by Nuchaz** [comment]
Actually, I just spent some time going over it and I had the same behavior in previous version too. What is happening is that hand is actually the minute hand and accurate to minecraft time in minutes. A minecraft minute is equal to 0.83 seconds, so that is why the hand movement seems faster than the pendulum. The pendulum is ticking in real time instead of minecraft time because it just feels more natural.  About all I can do in this case would be to sync the pendulum to the minute hand, but I am not sure I want to do that.
