### ISSUE TITLE
[1.10.2] Bookcase render glitch

### ISSUE THREAD

**Issue by DeadSix27** [Nuchaz/BiblioCraft#418]
BC Ver: BiblioCraft[v2.2.1][MC1.10.2].jar
Forge: forge-1.10.2-12.18.3.2234-universal.jar
Modlist: https://share.dsix.tech/modlist.txt

For some reason the bookcase turns into full block (hitbox is still halfed)

![image](https://cloud.githubusercontent.com/assets/1492505/23260393/f1760a66-f9d1-11e6-8944-c9ec8d134689.png)
![image](https://cloud.githubusercontent.com/assets/1492505/23260405/fd0e7b38-f9d1-11e6-9133-e434f47078af.png)

**Comment by Nuchaz** [comment]
I just finally ran into this today.  A restart of the minecraft client seemed to fix it. I am working on trying to figure this out.

**Comment by DeadSix27** [comment]
@Nuchaz Ye after restarting the client it disappeared for me as well, sorry for not mentioning that here, good to see you were able to reproduce this tho.

**Comment by Fokson** [comment]
I'll like to add to this, if I may.
Tool Racks: http://puu.sh/uDrCQ/e433695b24.jpg
Seats: http://puu.sh/uDrBg/752884008a.png
Tables: http://puu.sh/uDrCe/c8cb18ad10.png

Additionally, quartz plates only render items on them for about 6 seconds before appearing blank again, sword pedestals will occasionally render as the seats did, and the bookcases do the same for me as DeadSix.  While restarting the client fixes most of these issues, the table and the quartz plates persist no matter how many times I do so.

**Comment by MatthiasMann** [comment]
I had this issue too (also the painting machine was overlayed with a missign textured cube - but the corners of the real model showed through) - reloading the texture packs a few time (F3-T) fixes that.

**Comment by Nuchaz** [comment]
I have a fix in place for this that will be in the next update. I finally had it happen in my dev environment with some stuff setup so I could easily test some theories. It turns out, sometimes the game will fail get get one of my obj models and defaults to the missing model, when that happens, my model cache I built adds the missing model to the cache and just never checks to see if the model I am saving to the cache was even the right one. 

I have a fix in place for this and it will be in the next version (coming soon). I am updating the version for MC 1.10.2 while also adding the fixes to the version for MC 1.11.2, also coming soon.
