### ISSUE TITLE
Lock and Key - Color Chat Incompatibility

### ISSUE THREAD

**Issue by durand1w** [Nuchaz/BiblioCraft#429]
The Color Chat mod allows you to set a nickname and change the color of your name.  When using this in game, if your nickname or color change, you are not able to access locked Bibliocraft blocks.  Removing the nick and changing to the color you had at the time of setting the lock fixes the issue.  I'm not sure if Bibliocraft is using player ids, rather than player names to write lock information.

https://minecraft.curseforge.com/projects/colorchat

**Comment by Nuchaz** [comment]
I am using player names to write lock information, so that would be why. It probably would be safer to use player id's to do that. I'll see about adding support for that. I'll have to support ID's and names for awhile and pull name support down the road at a later version after everyone has already been using the ID's.

**Comment by durand1w** [comment]
No worries.  we had to abandon color chat for other reasons.
