### ISSUE TITLE
Bibliocraft v2.2.1 Packet Exploit

### ISSUE THREAD

**Issue by LXGaming** [Nuchaz/BiblioCraft#443]
A client can modify the NBT data of a 'Slotted Book' to have it contain any block or item they desire, They can then send a "Slotted Book" ItemStack with the modified NBT data to the server as a "BiblioUpdateInv" Packet.

On the server side this packet is handled by the method "handleInventoryStackUpdate", this method does have an item whitelist but because the "Slotted book" is apart of it the server then sets our modified ItemStack as the players currentItem.

A player can then open the book and retrieve the block or item.

**Comment by Nuchaz** [comment]
Ok, this will be fixed in the next update. I will roll this fix into the 1.7.10 version, the 1.10.2 version and the upcoming 1.11.2 version. I realized I don't even need to be sending ItemStacks in that packet, that's handled by the container already, so, no more ItemStacks through these packets anymore, that should stop that exploit.
