### ISSUE TITLE
Printing Press recipe Issues.

### ISSUE THREAD

**Issue by Placid-Storm** [Nuchaz/BiblioCraft#478]
I feel like an idiot for not noticing this sooner. Both Iron Block and Blaze Rod use B.

**Comment by Placid-Storm** [comment]
I edited the json and put it back in the jar. It works. I just replaced the "B" for Blaze Rod with "R".

[printingpress.txt](https://github.com/Nuchaz/BiblioCraft/files/1128895/printingpress.txt)

**Comment by Nuchaz** [comment]
derp, thanks for catching that, I'll get that fixed in the next release.

**Comment by Placid-Storm** [comment]
No problem. Did you see my pull request?

**Comment by Nuchaz** [comment]
yeah, I can't really accept it though because I am not doing recipes exactly that way. I have a separate Java based generator which I input a recipe in a similar way to what it was before so it really only takes one line of code. Then my generator takes care of the rest. There is way too many recipes to manually maintain. With this method I can make a small change in my generator if I need to affect all 400 or so recipes. You still helped show me exactly what was wrong so that made it easy to fix,  so thanks for that.

I plan to get another release out fairly soon. I am trying to figure out a couple of other fixes first.

**Comment by Nuchaz** [comment]
Just released an update with a fix for this.
