### ISSUE TITLE
about custom paint

### ISSUE THREAD

**Issue by MSteve3** [Nuchaz/BiblioCraft#702]
there is some glitch when i adding the picture, i still dont know why is happen (i readed the instruction many time but cant fix) :( 
(there is some pics to know about my issue) 
![image](https://user-images.githubusercontent.com/46162486/73134899-8e86ca80-406e-11ea-9222-49291bd228d0.png)
![image](https://user-images.githubusercontent.com/46162486/73134908-b9711e80-406e-11ea-90b5-bf5fbd638dd3.png)
(and yes i did change the file to .png file)
![image](https://user-images.githubusercontent.com/46162486/73134927-f2a98e80-406e-11ea-82bb-8890278c8e40.png)
(i added it to the mod, not add to the resource pack)

**Comment by EzerArch** [comment]
@MSteve3, I'm having the same issue. I maintain [this resource pack ](https://www.planetminecraft.com/texture_pack/aeon-extention-patch/)which supports Bibliocraft and adds huge paintings. I looked at the log:

`[08:13:35] [Client thread/INFO] [STDERR]: [jds.bibliocraft.helpers.PaintingUtil:getPaintingSetHeights:119]: java.io.FileNotFoundException: bibliocraft:textures/custompaintings/astronaut drifting far away.png`

But the actual filename is "**A**stronaut drifting far away.png". The mod finds the file in the resource pack with capitalized filename but the mod fails to load it because it tries to load it as uncapitalized filename. 

Also the mod or Minecraft seems to struggle to load and render images that aren't power of two (32x32, 64x64, 128x128 etc). If not power of two, they don't render as item but render as painting.

I suggest uncapitalizing filenames first. It worked for me.

![2020-03-10_09 05 43](https://user-images.githubusercontent.com/6743303/76310831-5817ae80-62ae-11ea-86e2-77861f2a6cc0.png)

Tweet: https://twitter.com/EzerArch/status/1237376319262019584

**Comment by MSteve3** [comment]
> @MSteve3, I'm having the same issue. I maintain [this resource pack ](https://www.planetminecraft.com/texture_pack/aeon-extention-patch/)which supports Bibliocraft and adds huge paintings. I looked at the log:
> 
> `[08:13:35] [Client thread/INFO] [STDERR]: [jds.bibliocraft.helpers.PaintingUtil:getPaintingSetHeights:119]: java.io.FileNotFoundException: bibliocraft:textures/custompaintings/astronaut drifting far away.png`
> 
> But the actual filename is "**A**stronaut drifting far away.png". The mod finds the file in the resource pack with capitalized filename but the mod fails to load it because it tries to load it as uncapitalized filename.
> 
> Also the mod or Minecraft seems to struggle to load and render images that aren't power of two (32x32, 64x64, 128x128 etc). If not power of two, they don't render as item but render as painting.
> 
> I suggest uncapitalizing filenames first. It worked for me.
> 
> ![2020-03-10_09 05 43](https://user-images.githubusercontent.com/6743303/76310831-5817ae80-62ae-11ea-86e2-77861f2a6cc0.png)

so can you tell me how to uncapitalizing filenames pls
my english skill is pretty bad so just easy to me

**Comment by EzerArch** [comment]
> so can you tell me how to uncapitalizing filenames pls

Examples:
- Rename "maid **M**onika.png" to "maid **m**onika.png"  (replace M with m)
- Rename "**M**onika in sundress.png" to "**m**onika in sundress.png"  (replace M with m)
- Rename "**S**teve's" to "steves" (replace S with s) and I would remove the apostrophe.

**Comment by MSteve3** [comment]
> > so can you tell me how to uncapitalizing filenames pls
> 
> Examples:
> 
> * Rename "maid **M**onika.png" to "maid **m**onika.png"  (replace M with m)
> * Rename "**M**onika in sundress.png" to "**m**onika in sundress.png"  (replace M with m)
> * Rename "**S**teve's" to "steves" (replace S with s) and I would remove the apostrophe.

tks bro
but i was reset my PC, so all my file are gone 
but still thank you

**Comment by gatoborrachon** [comment]
hey are you using optifine? because with Optifine any paint has this bug: https://imgur.com/a/BaEV1LO
